add quiet mode command-line option for parallel test
git-svn-id: https://svn.mcs.anl.gov/repos/parallel-netcdf/trunk@2698 c368ceb8-fd28-0410-a457-e46ee1d7cd4a

diff --git a/benchmarks/C/Makefile.in b/benchmarks/C/Makefile.in
--- a/benchmarks/C/Makefile.in
+++ b/benchmarks/C/Makefile.in
@@ -41,13 +41,14 @@ write_block_read_column: write_block_read_column.o $(LIBRARY)
 TEST_MPIRUN_4  = $(subst NP,4,$(TEST_MPIRUN))
 
 ptest: $(PROGS)
-	@for i in $(PROGS); do ( \
-	echo "-----------------------------------------------------" ; \
-	echo "$(TEST_MPIRUN_4) ./$$i 10 $(TEST_OUTDIR)/testfile.nc" ; \
-	echo "-----------------------------------------------------" ; \
-	$(TEST_MPIRUN_4) ./$$i 10 $(TEST_OUTDIR)/testfile.nc \
-	; ) ; done
-	@echo "-----------------------------------------------------"
+	@for i in $(PROGS); do { \
+	$(TEST_MPIRUN_4) ./$$i -q 10 $(TEST_OUTDIR)/testfile.nc ; \
+	if [ $$? = 0 ] ; then \
+	    echo "PASS:  C  parallel run on 4 processes --------------- $$i"; \
+	else \
+	    echo "FAILED:  C  parallel run on 4 processes ------------- $$i"; \
+	    exit 1; \
+	fi ; } ; done
 
 ptests:
 
