extend test to benchmark and examples

diff --git a/benchmarks/C/Makefile.am b/benchmarks/C/Makefile.am
--- a/benchmarks/C/Makefile.am
+++ b/benchmarks/C/Makefile.am
@@ -24,6 +24,11 @@ CLEANFILES = core core.* *.gcda *.gcno *.gcov gmon.out \
 
 TESTMPIRUN4  = `echo $(TESTMPIRUN) | $(SED) -e 's/NP/4/g'`
 
+if BUILD_DRIVER_BB
+TESTBB = 1
+TESTS_ENVIRONMENT = TESTBB=1 ; export TESTBB;
+endif
+
 ptest ptests ptest4: $(check_PROGRAMS)
 	for i in $(check_PROGRAMS); do { \
 	$(TESTMPIRUN4) ./$$i -q 10 $(TESTOUTDIR)/$$i.nc ; \
@@ -32,7 +37,19 @@ ptest ptests ptest4: $(check_PROGRAMS)
 	else \
 	    echo "FAILED:  C  parallel run on 4 processes ------------- $$i"; \
 	    exit 1; \
-	fi ; } ; done
+	fi ; \ 
+	if [ -n "$(TESTBB)" ]; then ( \
+        export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+        $(TESTMPIRUN4) ./$$i -q 10 $(TESTOUTDIR)/$$i.nc ; \
+        unset PNETCDF_HINTS ; \
+		if [ $$? = 0 ] ; then \
+			echo "PASS:  C  parallel run on 4 processes --------------- $$i"; \
+		else \
+			echo "FAILED:  C  parallel run on 4 processes ------------- $$i"; \
+			exit 1; \
+		fi ; \ 
+	) ; fi ; \
+	} ; done
 
 ptest2 ptest6 ptest8 ptest10:
 
diff --git a/benchmarks/FLASH-IO/Makefile.am b/benchmarks/FLASH-IO/Makefile.am
--- a/benchmarks/FLASH-IO/Makefile.am
+++ b/benchmarks/FLASH-IO/Makefile.am
@@ -60,6 +60,11 @@ CLEANFILES = core core.* *.gcda *.gcno *.gcov gmon.out \
              $(TESTOUTDIR)/flash_io_test_ncmpi_plt_crn_0000.nc \
              $(TESTOUTDIR)/flash_io_test_ncmpi_plt_cnt_0000.nc
 
+if BUILD_DRIVER_BB
+TESTBB = 1
+TESTS_ENVIRONMENT = TESTBB=1 ; export TESTBB;
+endif
+
 TESTMPIRUN4  = `echo $(TESTMPIRUN) | $(SED) -e 's/NP/4/g'`
 
 ptests ptest ptest4: $(check_PROGRAMS)
@@ -68,7 +73,17 @@ ptests ptest ptest4: $(check_PROGRAMS)
 	    echo "PASS: F90 parallel run on 4 processes --------------- FLASH_IO"; \
 	else \
 	    echo "FAILED: F90 parallel run on 4 processes ------------- FLASH_IO"; \
-	fi
+	fi ; \
+    if [ -n "$(TESTBB)" ]; then ( \
+        export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+        $(TESTMPIRUN4) ./$(check_PROGRAMS) $(RUN_QUIETLY) $(TESTOUTDIR)/flash_io_test_ ; \
+        unset PNETCDF_HINTS ; \
+        if [ $$? = 0 ] ; then \
+            echo "PASS: F90 parallel run on 4 processes --------------- FLASH_IO"; \
+        else \
+            echo "FAILED: F90 parallel run on 4 processes ------------- FLASH_IO"; \
+        fi ; \
+	) ; fi 
 
 ptest2 ptest6 ptest8 ptest10:
 
diff --git a/examples/C/Makefile.am b/examples/C/Makefile.am
--- a/examples/C/Makefile.am
+++ b/examples/C/Makefile.am
@@ -44,6 +44,7 @@ check_PROGRAMS = collective_write \
 if BUILD_DRIVER_BB
 TESTBB = 1
 TESTS_ENVIRONMENT = TESTBB=1 ; export TESTBB;
+AM_CPPFLAGS += -DBUILD_DRIVER_BB
 endif
 
 NC_FILES = $(check_PROGRAMS:%=$(TESTOUTDIR)/%.nc)
@@ -101,7 +102,23 @@ ptest8: $(check_PROGRAMS)
         else \
            echo "FAILED:  C  parallel run on 8 processes ------------- $$i"; \
 	   exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                if [ $$i = "get_vara" ] ; then \
+                        $(TESTMPIRUN8) ./$$i -q $(TESTOUTDIR)/put_vara.nc ; \
+                else \
+                        $(TESTMPIRUN8) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                fi ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS:  C  parallel run on 8 processes --------------- $$i"; \
+                else \
+                        echo "FAILED:  C  parallel run on 8 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptest3: $(check_PROGRAMS)
 	for j in 0 1 ; do { \
@@ -117,7 +134,23 @@ ptest3: $(check_PROGRAMS)
         else \
            echo "FAILED:  C  parallel run on 3 processes ------------- $$i"; \
 	   exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                if [ $$i = "get_vara" ] ; then \
+                        $(TESTMPIRUN3) ./$$i -q $(TESTOUTDIR)/put_vara.nc ; \
+                else \
+                        $(TESTMPIRUN3) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                fi ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS:  C  parallel run on 3 processes --------------- $$i"; \
+                else \
+                        echo "FAILED:  C  parallel run on 3 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptests: ptest3 ptest4 ptest8
 ptest2 ptest6 ptest10:
diff --git a/examples/F77/Makefile.am b/examples/F77/Makefile.am
--- a/examples/F77/Makefile.am
+++ b/examples/F77/Makefile.am
@@ -39,6 +39,12 @@ utils.o: $(srcdir)/utils.F90
 # parallel runs only
 # TESTS = $(check_PROGRAMS)
 
+if BUILD_DRIVER_BB
+TESTBB = 1
+TESTS_ENVIRONMENT = TESTBB=1 ; export TESTBB;
+AM_FFLAGS += -DBUILD_DRIVER_BB -cpp
+endif
+
 NC_FILES = $(check_PROGRAMS:%=$(TESTOUTDIR)/%.nc)
 
 CLEANFILES = core core.* *.gcda *.gcno *.gcov gmon.out \
@@ -58,7 +64,19 @@ ptest ptest4: $(check_PROGRAMS)
         else \
            echo "FAILED: F77 parallel run on 4 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                $(TESTMPIRUN4) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS: F77 parallel run on 4 processes --------------- $$i"; \
+                else \
+                        echo "FAILED: F77 parallel run on 4 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptest8: $(check_PROGRAMS)
 	for j in 0 1 ; do { \
@@ -70,7 +88,19 @@ ptest8: $(check_PROGRAMS)
         else \
            echo "FAILED: F77 parallel run on 8 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                $(TESTMPIRUN8) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS: F77 parallel run on 8 processes --------------- $$i"; \
+                else \
+                        echo "FAILED: F77 parallel run on 8 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptest3: $(check_PROGRAMS)
 	for j in 0 1 ; do { \
@@ -82,7 +112,19 @@ ptest3: $(check_PROGRAMS)
         else \
            echo "FAILED: F77 parallel run on 3 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                $(TESTMPIRUN3) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS: F77 parallel run on 3 processes --------------- $$i"; \
+                else \
+                        echo "FAILED: F77 parallel run on 3 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptests: ptest3 ptest4 ptest8
 ptest2 ptest6 ptest10:
diff --git a/examples/tutorial/Makefile.am b/examples/tutorial/Makefile.am
--- a/examples/tutorial/Makefile.am
+++ b/examples/tutorial/Makefile.am
@@ -45,6 +45,14 @@ endif
 # parallel runs only
 # TESTS = $(check_PROGRAMS)
 
+if BUILD_DRIVER_BB
+TESTBB = 1
+TESTS_ENVIRONMENT = TESTBB=1 ; export TESTBB;
+AM_CPPFLAGS += -DBUILD_DRIVER_BB
+AM_FFLAGS += -DBUILD_DRIVER_BB
+AM_FCFLAGS += -DBUILD_DRIVER_BB
+endif
+
 NC_FILES = $(check_PROGRAMS:%=$(TESTOUTDIR)/%.nc)
 
 CLEANFILES = core core.* *.gcda *.gcno *.gcov gmon.out \
@@ -75,7 +83,31 @@ ptest ptest4: $(check_PROGRAMS)
         else \
            echo "FAILED:     parallel run on 4 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                if [ $$i = "pnetcdf-read-from-master" ] ; then \
+                        $(TESTMPIRUN4) ./$$i $(TESTOUTDIR)/pnetcdf-write-from-master.nc ; \
+                elif [ $$i = "pnetcdf-read-nfiles" ] ; then \
+                        $(TESTMPIRUN4) ./$$i $(TESTOUTDIR)/pnetcdf-write-nfiles.nc ; \
+                elif [ $$i = "pnetcdf-read-standard" ] ; then \
+                        $(TESTMPIRUN4) ./$$i $(TESTOUTDIR)/pnetcdf-write-standard.nc ; \
+                elif [ $$i = "pnetcdf-read-flexible" ] ; then \
+                        $(TESTMPIRUN4) ./$$i $(TESTOUTDIR)/pnetcdf-write-flexible.nc ; \
+                elif [ $$i = "pnetcdf-read-nb" ] ; then \
+                        $(TESTMPIRUN4) ./$$i $(TESTOUTDIR)/pnetcdf-write-nb.nc ; \
+                else \
+                        $(TESTMPIRUN4) ./$$i $(TESTOUTDIR)/$$i.nc ; \
+                fi ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS:     parallel run on 4 processes --------------- $$i"; \
+                else \
+                        echo "FAILED:     parallel run on 4 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptests: ptest4
 ptest2 ptest3 ptest6 ptest8 ptest10:
