add return value and revise stdout for make ptest
git-svn-id: https://svn.mcs.anl.gov/repos/parallel-netcdf/trunk@1958 c368ceb8-fd28-0410-a457-e46ee1d7cd4a

diff --git a/examples/F77/Makefile.in b/examples/F77/Makefile.in
--- a/examples/F77/Makefile.in
+++ b/examples/F77/Makefile.in
@@ -87,31 +87,35 @@ TEST_MPIRUN_3  = $(subst NP,3,$(TEST_MPIRUN))
 
 ptest: $(PROGS)
 	@for i in $(PROGS); do ( \
-	echo "-----------------------------------------------------" ; \
-	echo "$(TEST_MPIRUN_4) ./$$i -q $(TEST_OUTDIR)/testfile.nc" ; \
-	echo "-----------------------------------------------------" ; \
-	$(TEST_MPIRUN_4) ./$$i -q $(TEST_OUTDIR)/testfile.nc \
-	; ) ; done
+        $(TEST_MPIRUN_4) ./$$i -q $(TEST_OUTDIR)/testfile.nc ; \
+        if [ $$? = 0 ] ; then \
+           echo "PASS: parallel run on 4 processes ------------------- $$i"; \
+        else \
+           echo "FAILED: parallel run on 4 processes ----------------- $$i"; \
+        fi ; ) ; done
 
 ptests: $(PROGS)
 	@for i in $(PROGS); do ( \
-	echo "-----------------------------------------------------" ; \
-	echo "$(TEST_MPIRUN_4) ./$$i -q $(TEST_OUTDIR)/testfile.nc" ; \
-	echo "-----------------------------------------------------" ; \
-	$(TEST_MPIRUN_4) ./$$i -q $(TEST_OUTDIR)/testfile.nc \
-	; ) ; done
+        $(TEST_MPIRUN_4) ./$$i -q $(TEST_OUTDIR)/testfile.nc ; \
+        if [ $$? = 0 ] ; then \
+           echo "PASS: parallel run on 4 processes ------------------- $$i"; \
+        else \
+           echo "FAILED: parallel run on 4 processes ----------------- $$i"; \
+        fi ; ) ; done
 	@for i in $(PROGS); do ( \
-	echo "-----------------------------------------------------" ; \
-	echo "$(TEST_MPIRUN_8) ./$$i -q $(TEST_OUTDIR)/testfile.nc" ; \
-	echo "-----------------------------------------------------" ; \
-	$(TEST_MPIRUN_8) ./$$i -q $(TEST_OUTDIR)/testfile.nc \
-	; ) ; done
+        $(TEST_MPIRUN_8) ./$$i -q $(TEST_OUTDIR)/testfile.nc ; \
+        if [ $$? = 0 ] ; then \
+           echo "PASS: parallel run on 8 processes ------------------- $$i"; \
+        else \
+           echo "FAILED: parallel run on 8 processes ----------------- $$i"; \
+        fi ; ) ; done
 	@for i in $(PROGS); do ( \
-	echo "-----------------------------------------------------" ; \
-	echo "$(TEST_MPIRUN_3) ./$$i -q $(TEST_OUTDIR)/testfile.nc" ; \
-	echo "-----------------------------------------------------" ; \
-	$(TEST_MPIRUN_3) ./$$i -q $(TEST_OUTDIR)/testfile.nc \
-	; ) ; done
+        $(TEST_MPIRUN_3) ./$$i -q $(TEST_OUTDIR)/testfile.nc ; \
+        if [ $$? = 0 ] ; then \
+           echo "PASS: parallel run on 3 processes ------------------- $$i"; \
+        else \
+           echo "FAILED: parallel run on 3 processes ----------------- $$i"; \
+        fi ; ) ; done
 
 include $(srcdir)/depend
 include $(srcdir)/../../rules.make
diff --git a/examples/tutorial/Makefile.in b/examples/tutorial/Makefile.in
--- a/examples/tutorial/Makefile.in
+++ b/examples/tutorial/Makefile.in
@@ -91,13 +91,14 @@ pnetcdf-permute: pnetcdf-permute.o $(LIBRARY)
 
 TEST_MPIRUN_4  = $(subst NP,4,$(TEST_MPIRUN))
 
-ptest: $(PROGS)
+ptest ptests: $(PROGS)
 	@for i in $(PROGS); do ( \
-	echo "-----------------------------------------------------" ; \
-	echo "$(TEST_MPIRUN_4) ./$$i $(TEST_OUTDIR)/testfile.nc" ; \
-	echo "-----------------------------------------------------" ; \
-	$(TEST_MPIRUN_4) ./$$i $(TEST_OUTDIR)/testfile.nc \
-	; ) ; done
+        $(TEST_MPIRUN_4) ./$$i $(TEST_OUTDIR)/testfile.nc ; \
+        if [ $$? = 0 ] ; then \
+           echo "PASS: parallel run on 4 processes ------------------- $$i"; \
+        else \
+           echo "FAILED: parallel run on 4 processes ----------------- $$i"; \
+        fi ; ) ; done
 
 include $(srcdir)/depend
 include $(srcdir)/../../rules.make
