extend test to benchmark and examples

diff --git a/examples/F90/Makefile.am b/examples/F90/Makefile.am
--- a/examples/F90/Makefile.am
+++ b/examples/F90/Makefile.am
@@ -34,6 +34,12 @@ utils.o: utils.F90
 # parallel runs only
 # TESTS = $(check_PROGRAMS)
 
+if BUILD_DRIVER_BB
+TESTBB = 1
+TESTS_ENVIRONMENT = TESTBB=1 ; export TESTBB;
+AM_FCFLAGS += -DBUILD_DRIVER_BB -cpp
+endif
+
 NC_FILES = $(check_PROGRAMS:%=$(TESTOUTDIR)/%.nc)
 
 CLEANFILES = core core.* *.gcda *.gcno *.gcov gmon.out \
@@ -53,7 +59,19 @@ ptest ptest4: $(check_PROGRAMS)
         else \
            echo "FAILED: F90 parallel run on 4 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                $(TESTMPIRUN4) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS: F90 parallel run on 4 processes --------------- $$i"; \
+                else \
+                        echo "FAILED: F90 parallel run on 4 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptest8: $(check_PROGRAMS)
 	for j in 0 1 ; do { \
@@ -65,7 +83,19 @@ ptest8: $(check_PROGRAMS)
         else \
            echo "FAILED: F90 parallel run on 8 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                $(TESTMPIRUN8) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS: F90 parallel run on 8 processes --------------- $$i"; \
+                else \
+                        echo "FAILED: F90 parallel run on 8 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptest3: $(check_PROGRAMS)
 	for j in 0 1 ; do { \
@@ -77,7 +107,19 @@ ptest3: $(check_PROGRAMS)
         else \
            echo "FAILED: F90 parallel run on 3 processes ------------- $$i"; \
            exit 1; \
-        fi ; } ; done ; } ; done
+        fi ; \
+        if [ -n "$(TESTBB)" ]; then ( \
+                export PNETCDF_HINTS="nc_bb=enable;nc_bb_dirname=${TESTOUTDIR};nc_bb_overwrite=enable" ; \
+                $(TESTMPIRUN3) ./$$i -q $(TESTOUTDIR)/$$i.nc ; \
+                unset PNETCDF_HINTS ; \
+                if [ $$? = 0 ] ; then \
+                        echo "PASS: F90 parallel run on 3 processes --------------- $$i"; \
+                else \
+                        echo "FAILED: F90 parallel run on 3 processes ------------- $$i"; \
+                        exit 1; \
+                fi ; \
+	) ; fi ; \
+        } ; done ; } ; done
 
 ptests: ptest3 ptest4 ptest8
 ptest2 ptest6 ptest10:
