This revision is mainly to support the new data types introduced in CDF-5 specification: UBYTE, USHORT, UINT, INT64, and UINT64
1. Support the following CDF-5 data types for C APIs:
   unsigned short, unsigned int, 64-bit integer (int64), unsigned int64
   New APIs: ncmpi_put_vara_ushort(), ncmpi_put_vara_uint(),
             ncmpi_put_vara_longlong(), and ncmpi_put_vara_ulonglong(), etc.

2. Support the following CDF-5 data types for Fortran APIs:
   64-bit integer (int8)
   New APIs: nfmpi_put_vara_int8(), etc.

3. The new APIs follow the looks of netCDF4.

4. Extend test program, nc_test and nf_test, to test the new data types.
   Note that for data types int64 and uint64, test for out-of-bound values
   are disabled, as no bigger data type can be used to do such tests. I
   simply test those data types using numbers slightly larger and smaller
   than the 32-bit integer min and max.

5. Use C defined macros to shorted lines of codes for different data types.
   This applies for all APIs.

6. Remove ncmpi_type. Just use nc_type.

7. Break ncx.c into files. One for each variable data type in file.
   getputn_schar.c, getputn_uchar.c,  getputn_short.c, getputn_int.c,
   getputn_float.c, getputn_double.c, getputn_ushort.c,
   getputn_uint.c,  getputn_int64.c,  getputn_uint64.c



git-svn-id: https://svn.mcs.anl.gov/repos/parallel-netcdf/trunk@989 c368ceb8-fd28-0410-a457-e46ee1d7cd4a

diff --git a/src/libf/createffiles b/src/libf/createffiles
--- a/src/libf/createffiles
+++ b/src/libf/createffiles
@@ -4,19 +4,25 @@
 # This is a simple script that creates the Fortran interface files.
 # It makes use of an interface builder developed for MPICH2 and a set of 
 # NetCDF-specific descriptions in the file "defs".
-mpich2SourceDir=${MPICH2SRC:-/home/d_cluster/src/MPICH/mpich2-1.2.1}
+if [ -z "$BUILDIFACE" ] ; then
+    mpich2SourceDir=${MPICH2SRC:-/home/d_cluster/src/MPICH/mpich2-1.2.1}
 
-if [ ! -d "$mpich2SourceDir" ] ; then
-    echo "Set the environment variable MPICH2SRC to the root directory for mpich2"
-    exit 1
+    if [ ! -d "$mpich2SourceDir" ] ; then
+        echo "Set the environment variable MPICH2SRC to the root directory for mpich2"
+        exit 1
+    fi
+    if [ ! -x $mpich2SourceDir/src/binding/f77/buildiface ] ; then
+        echo "Cannot find $mpich2SourceDir/src/binding/f77/buildiface"
+        exit 1
+    fi
 fi
-if [ ! -x $mpich2SourceDir/src/binding/f77/buildiface ] ; then
-    echo "Cannot find $mpich2SourceDir/src/binding/f77/buildiface"
-    exit 1
+if [ ! -x $BUILDIFACE ] ; then
+        echo "Cannot find $BUILDIFACE"
+        exit 1
 fi
 
 # Build the files 
-$mpich2SourceDir/src/binding/f77/buildiface -infile=../lib/pnetcdf.h -deffile=defs $@
+$BUILDIFACE -infile=../lib/pnetcdf.h -deffile=defs $@
 # Update to the old name
 for file in *f.c mpifnetcdf.h ; do
     if grep FORT_DLL_SPEC $file >/dev/null 2>&1 ; then 
